import { PERSONAS } from './constants';

// ─── Date Formatting ─────────────────────────────────────────────
export const formatDate = (dateStr) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  });
};

export const formatDuration = (seconds) => {
  if (!seconds) return '—';
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
};

export const timeAgo = (dateStr) => {
  const date = new Date(dateStr);
  const now = new Date();
  const diff = Math.floor((now - date) / 1000);
  if (diff < 60) return 'just now';
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
};

// ─── Debate Export ───────────────────────────────────────────────
export const exportDebateAsMarkdown = (topic, messages) => {
  const lines = [
    `# PanelGPT Debate: ${topic}`,
    `*Exported on ${new Date().toLocaleDateString()}*`,
    '',
    '---',
    '',
  ];

  messages.forEach((msg) => {
    const persona = PERSONAS[msg.personaId];
    const icon = persona?.icon || '🤖';
    const role = persona?.role || msg.personaId;
    lines.push(`## ${icon} ${msg.personaName} — *${role}*`);
    lines.push('');
    lines.push(msg.content);
    lines.push('');
    lines.push('---');
    lines.push('');
  });

  lines.push(`*Generated by PanelGPT | panelgpt.local*`);
  return lines.join('\n');
};

export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const el = document.createElement('textarea');
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    return true;
  }
};

// ─── Keyword Extraction ──────────────────────────────────────────
export const extractKeyPhrases = (messages, maxPhrases = 6) => {
  const stopWords = new Set([
    'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
    'of', 'with', 'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been',
    'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
    'should', 'may', 'might', 'can', 'this', 'that', 'these', 'those',
    'it', 'its', 'we', 'our', 'they', 'their', 'i', 'my', 'you', 'your',
    'not', 'no', 'as', 'if', 'so', 'yet', 'than', 'then', 'when', 'where',
  ]);

  const wordCount = {};
  messages.forEach((msg) => {
    const words = msg.content.toLowerCase()
      .replace(/[^a-z\s]/g, ' ')
      .split(/\s+/)
      .filter(w => w.length > 4 && !stopWords.has(w));

    words.forEach(w => { wordCount[w] = (wordCount[w] || 0) + 1; });
  });

  return Object.entries(wordCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, maxPhrases)
    .map(([word]) => word);
};

// ─── Avatar Color ────────────────────────────────────────────────
export const getInitials = (name) => {
  if (!name) return 'U';
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);
};

// ─── Validation ──────────────────────────────────────────────────
export const validateEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
export const validatePassword = (pwd) => pwd.length >= 8 && /\d/.test(pwd);
export const validateUsername = (u) => /^[a-zA-Z0-9_]{3,50}$/.test(u);
